---
title: "1. Pojęcie obrony cywilnej"
format: html
---

<br>

## Etymologia

W ujęciu encyklopedycznym (PWN) **„obrona”** to zespół działań o charakterze prawnym, polegających na odpieraniu ataku lub łagodzeniu jego skutków. Obejmuje ona zarówno **uprawnienia formalne** (np. prawo do ochrony), jak i **środki materialne** – wszystkie narzędzia dopuszczone przez prawo, które służą zapewnieniu sprawiedliwego wyniku działań obronnych.

Z kolei określenie **„cywilna”** pochodzi od łacińskiego *civis* (obywatel) i pierwotnie odnosi się do ochrony osób nieuczestniczących bezpośrednio w działaniach wojennych. Według definicji W. Kitlera, obrona cywilna to „opór i obrona ludności cywilnej, walka cywilna, przeciwstawianie się niebezpieczeństwom, samoobrona społeczna i pomoc wzajemna” – a więc zarówno zorganizowane działania administracyjne, jak i aktywność obywateli.

**Obrona cywilna** tworzy strukturę złożoną z sił i środków, będących elementami systemu operacyjnego wsparcia zarówno na poziomie lokalnym, jak i krajowym czy międzynarodowym. System ten realizuje zadania z zakresu ochrony ludności i ratownictwa, a także uwzględnia wzajemne powiązania między tymi działaniami.

W takim ujęciu obrona cywilna stanowi część szerszego **systemu ochrony społeczeństwa**, będącego ogniwem organizacyjnym struktur państwowych i ponadnarodowych. Obejmuje ona system instytucji, organy kierowania, służby ratownicze oraz elementy organizacyjne, których celem jest **zapewnienie pomocy ludności w sytuacjach kryzysowych oraz ciągłe doskonalenie zdolności reagowania na zagrożenia**.
